//! Stamps the Windows executable with the app icon and version information.
//!
//! Windows takes an .exe's icon from its resources, not from the code, so
//! without this the file shows up with the generic application icon in
//! Explorer and the Start menu even though the window itself draws the logo.
//!
//! Compiling the resource needs `rc.exe` from the Windows SDK. If it is not
//! installed we warn and carry on: a build without resources is still a
//! perfectly good build, and failing here would be a hostile way to find out.

use std::path::PathBuf;
use std::process::Command;

/// Relative to this crate's root.
const ICON: &str = "../../assets/logo/mapleview-icon.ico";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={ICON}");

    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    let Some(rc) = find_rc() else {
        println!(
            "cargo:warning=rc.exe not found (install the Windows SDK); \
             building without an .exe icon or version resource"
        );
        return;
    };

    let crate_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    let icon = crate_dir.join(ICON);
    if !icon.exists() {
        println!(
            "cargo:warning={} is missing; skipping the .exe resource",
            icon.display()
        );
        return;
    }

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets this"));
    let script = out_dir.join("mapleview.rc");
    let compiled = out_dir.join("mapleview.res");
    if let Err(error) = std::fs::write(&script, utf16_with_bom(&resource_script(&icon))) {
        println!(
            "cargo:warning=could not write {}: {error}",
            script.display()
        );
        return;
    }

    let output = Command::new(&rc)
        .arg("/nologo")
        .arg("/fo")
        .arg(&compiled)
        .arg(&script)
        .output();
    match output {
        Ok(output) if output.status.success() => {}
        Ok(output) => {
            let stderr = String::from_utf8_lossy(&output.stderr);
            println!("cargo:warning=rc.exe failed, building without resources: {stderr}");
            return;
        }
        Err(error) => {
            println!("cargo:warning=could not run {}: {error}", rc.display());
            return;
        }
    }

    // link.exe treats a .res file as just another input, so handing it over as
    // a link argument is all it takes.
    println!("cargo:rustc-link-arg={}", compiled.display());
}

/// The resource script, as a string. Written out as UTF-16LE because that is
/// what `rc.exe` reads without having to be told a code page, and the strings
/// here are Chinese.
fn resource_script(icon: &std::path::Path) -> String {
    let version = std::env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".into());
    let mut parts = version
        .split('.')
        .map(|part| part.parse::<u16>().unwrap_or(0));
    let major = parts.next().unwrap_or(0);
    let minor = parts.next().unwrap_or(0);
    let patch = parts.next().unwrap_or(0);
    let icon = icon.display().to_string().replace('\\', "\\\\");

    format!(
        r#"// Generated by build.rs -- edit that instead.
#define IDI_MAPLEVIEW 1
IDI_MAPLEVIEW ICON "{icon}"

#define VS_VERSION_INFO 1
#define VS_FFI_FILEFLAGSMASK 0x3fL
#define VFT_APP 0x00000001L
#define VFT2_UNKNOWN 0x00000000L
#define VOS_NT_WINDOWS32 0x00040004L

VS_VERSION_INFO VERSIONINFO
 FILEVERSION {major},{minor},{patch},0
 PRODUCTVERSION {major},{minor},{patch},0
 FILEFLAGSMASK VS_FFI_FILEFLAGSMASK
 FILEFLAGS 0x0L
 FILEOS VOS_NT_WINDOWS32
 FILETYPE VFT_APP
 FILESUBTYPE VFT2_UNKNOWN
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "080404B0"
        BEGIN
            VALUE "CompanyName", "Terry"
            VALUE "FileDescription", "枫阅图片查看器"
            VALUE "FileVersion", "{version}"
            VALUE "InternalName", "mapleview"
            VALUE "LegalCopyright", "MIT Licensed"
            VALUE "OriginalFilename", "mapleview.exe"
            VALUE "ProductName", "枫阅 MapleView"
            VALUE "ProductVersion", "{version}"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x804, 1200
    END
END
"#
    )
}

fn utf16_with_bom(text: &str) -> Vec<u8> {
    let mut bytes = vec![0xff, 0xfe];
    for unit in text.encode_utf16() {
        bytes.extend_from_slice(&unit.to_le_bytes());
    }
    bytes
}

/// `rc.exe` from the Windows SDK: an explicit override, then `PATH`, then the
/// newest SDK on disk.
fn find_rc() -> Option<PathBuf> {
    if let Some(path) = std::env::var_os("MAPLEVIEW_RC") {
        let path = PathBuf::from(path);
        if path.is_file() {
            return Some(path);
        }
    }

    if let Some(path) = which("rc.exe") {
        return Some(path);
    }

    let arch = match std::env::var("TARGET").as_deref() {
        Ok(target) if target.starts_with("aarch64") => "arm64",
        Ok(target) if target.starts_with("i686") => "x86",
        _ => "x64",
    };
    let kits = PathBuf::from(r"C:\Program Files (x86)\Windows Kits\10\bin");
    let mut versions: Vec<_> = std::fs::read_dir(&kits)
        .ok()?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.join(arch).join("rc.exe").is_file())
        .collect();
    versions.sort();
    versions.pop().map(|path| path.join(arch).join("rc.exe"))
}

fn which(exe: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    std::env::split_paths(&path)
        .map(|dir| dir.join(exe))
        .find(|candidate| candidate.is_file())
}
